trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - script: |
      # Install dependencies
      pip install -r requirements.txt
    displayName: 'Install dependencies'

  - script: |
      # Run tests
      pytest
    displayName: 'Run tests'

  - script: |
      # Build Docker image
      docker build -t kangsumang/python_project:latest .
    displayName: 'Build Docker image'
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))

  - task: Docker@2
    inputs:
      containerRegistry: 'kangsumang'
      repository: 'python_project'
      command: 'push'
      tags: 'latest'
    displayName: 'Push Docker image'
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))

